services:
  app:
    build:
      context: .
    ports:
      - "12000:3000"
    tty: true
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
    command: npm run dev
  db:
    image: postgres:12-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres: